language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Bb8iBD6H5yDMF3GEu7qShgAI6has6cpRVOBbq0VMaWokFRPSictzDHsmzx3YDcJFKdyBIPUsVa5b6oXvadbUtdHR3Dcn7fwuGKaCzBj/YGRNow2OI+PoawZkwhtecjY8Z9RUhBWkACHmCx7iNjXR7Q6A/cYqrtYt0HpwZoAViVfE5etYMPbw9y0fWGZyG5tlaOCCNudW2Qk9hTGf2BwGK97yVn6yfExycFe7Ydf2uv+qVuMgK7Bv7nHPNfIOJRP8ikZ5wgPdIXDfOS6bvKthHV2eSQrupEECTcBFH7/9mmnevemGwmvpjBHAxXDMaHgaDzp1vhXVwsQydwXhV7olBnMNwzHgCRQ9ZUQXut1xahD7PCwyYHq0Ds0BMGmOPecYTb+fNEa13Osqer2WG4Nun/WfXKBYtu8wZ96Ow3XftRwZwkYEzJBQvm4XFLBpHPYBAWtP7iHJvwcd3pbzB7dXg4Zystbr4aenyy7IazHL8/MQT0J38AX2aktxytz6NT2/0BLnggg95eUjeKKNJj153QV1Hi3gYOrI+VqxN4uRBpmO2icU/3O4TA1JYZPWp5i/YbKGjoOU9MFv+GGxwFrhmPPQk3ODAZLbd3o+JqqQGPF9GCz8ljZuktKYIYIpgxzkcTH47TqbnpelTFRqEkVjXsSUSDEa1m2+cPy1cxEQy/c=
  app: kevin-noteful-v3
  on:
    repo: thinkful-ei19/kevin-noteful-v3
