language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: lbxeb4yFGoog4tuZwKRN+FwBPv+J0b2Lgfmk7Sm43M9IClopjOXVD71yrSW5eTPkEnBxYlEqGyz0Qpf0Y8G//Zi59L7opI/lXoV079xD4qMeO0iZeTX2szwXkgT7WYKix7G+MIDR3809KWzkSHiS3VbwM1aOaajVcdjZgKPu+SuOeLOLCLh2Rk9TOLEa8JWrk9SqMOJCDlMeSeQ0MjLfeJLiS58BOI2exEUdAqA+wNUGTBuPfjYjuhDS/szoEIpLXhzwfODtbRz9o+VZYOMX2bkwCsmpGfksreO97vMATTN6wq6hBCkgXL3g43eFGvbn9Ld/jn2Tw1AESljWzCYI2kwMfdXS1LwS2JMqD0GCrSYbF7ErGZbyVEdj7M1GABxYe47UoxlJm3bfJtW6ovqQAZnOxebwvYfSITvsi/JQLcRmLyJ3eC6LTwfbUsyR/fn3bO+j/WXz6kD0tV1WJQDZU7bNNMv3flT7ltC2gLwSyo3cvMZIzM28rNIobNcGtTHqaIrnl5ZAoS05i5Qq5no4z69oLpeg6rpP7MonSqSVqJXdBPBJY/n2Uht5CZ+TLk78ADdLZHTTAaRV4/sCb2b02Y5kgOfL8kV6S0L0dZZkV5+MhYE5+nTacvsmapWpgO01MPn2hUesb9peJFSnQ8jRjEkAew812pakp+lYiQ/wavI=
  app: kevin-noteful-v3
  on:
    repo: thinkful-ei19/kevin-noteful-v3
