language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: J2WkMQ0Wa8STahY9PiH1XIvzN+EJjhv2nX7ljCaHlHxUddoHOeqjw6+hAExTsxoKBYQxT+MgY6RwVFosaaKRvSCPeojaVT6qMUHNdhprbxKpy67bAhUxpMnXhPkYbvdiuW5qUXHXc8I16w8E1TPJh6N9kP49QGd1EVpzeOctfO2qYH1WNsf9hx/y9vZeITVkf7rIummtV0MslmPj5ufQru6uJ/lRlOMjCUILdIGEMlgK/2MH/i8ynkP0mGSHrGdSgmKaa/0FIR/e20JYEZ7yXtQ1M9OqTqfI5GiXuESURZezqglcU5k/xzf4hWvD94oW9wYV01cwkAPgEeOwOxZxFIgeRFa/DTIX/cXleDlwizj6s3ez3BiLVLYxuzSyGpxatQL6lAE+CHsrfhXe0fYQWj26ge6jRS1zAA8GvcPhRFUSnU5Dklu2jCTU6760mEG2fuJ6aVYaq60B0PurfNNrhuyqMB5yKAp/NSgHAcNzy2bCIN16sW/wBkDzy6dRul+bp1CubhUgCgAoJui19V17PvsadcaMyfLjsbVYVrlJp6S5hkbIt9hz8iDNNJHijEoY0PR1kXXVEKsNsfB3jhTK63/99D3XK+uld7y/a4lm7+9Xav36OLHlKeRFVupSgc5xPsV3rRGtnIIVwrfQAUL5/U8a9RKCBuH0KEPcTkpJ0Yc=
  app: kevin-noteful-v3
  on:
    repo: thinkful-ei19/kevin-noteful-v3 
